### ISSUE TITLE
wr latest release

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/npg_conda#12]
https://github.com/VertebrateResequencing/wr

To clarify what golang version we need. The one that unstalls with apt-get on Xenial is 1.6.2; it seems too low. We might want golang installed as well.

**Comment by sb10** [comment]
Do you need to build wr yourself? I'd suggest just downloading the release .zip and extracting wr from there. It's a static binary with no dependencies.

(But yes, 1.6.2 is too low; you want 1.8 or higher)

**Comment by keithj** [comment]
Fixed by #13
