### ISSUE TITLE
Support for semantic versioning

### ISSUE THREAD

**Issue by jmtcsngr** [wtsi-npg/npg_conda#123]
I was trying to build a package with version `x.y.z-beta` and a parser failed to understand the version. I think it is because we only allow numeric characters and '-' was the first thing it found to upset it. Maybe beta is also going to be a problem. I was wondering if we are interested in supporting full semantic versions?

**Comment by jmtcsngr** [comment]
Digging into this I found `x.y.z-beta` is not valid according to pep440. And the version parser we use is based on pep440 as far as I can see. Instead `x.y.zbn` should be the compatible way to express the version.

**Comment by kjsanger** [comment]
Closing as we're using Conda's version-handling code.
