### ISSUE TITLE
Consider adding core dump to samtools

### ISSUE THREAD

**Issue by jmtcsngr** [wtsi-npg/npg_conda#125]
@mgcam is asking if it will be possible to create next samtools recipe with support for core dumping?

**Comment by kjsanger** [comment]
Do you mean a `-g` build? Does that also mean `htslib`? There is already a Conda config file for setting `CFLAGS` etc (https://github.com/wtsi-npg/npg_conda/blob/devel/conda_build_config.yaml) so this is more of a build-time config question. It doesn't require changing the recipes

**Comment by kjsanger** [comment]
If the default core dump location is a problem, we can change `/proc/sys/kernel/core_pattern` (execpt perhaps on RedHat if `abrt` is in use).

**Comment by jmtcsngr** [comment]
This came from a question from @mgcam, guess we can build with the right flags. Not sure if we want the core dumps everywhere though. Do you recommend using different versions of the package? One with core dump, one without? The htslib question is good. I guess we need both to get the whole story. The location of the dumps is a good question. Not sure how to do it. Thought by default they will dump in the pwd

**Comment by mgcam** [comment]
http://man7.org/linux/man-pages/man5/core.5.html as a reference. Looks 
like we need to  have unique names for these files, which is nor 
difficult. Changing location seems less straightforward. But might be 
possible where we have more control, ie 'On systems that employ 
systemd(1) as the init framework, core dumps may instead be placed in a 
location determined by systemd(1).'





-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by kjsanger** [comment]
Location issue answered above. We only need one version of the package. The downside is only that the binaries will be a bit bigger, but we can cope with that.

**Comment by kjsanger** [comment]
`htslib`, `samtools` and `bcftools` already have `-g` in their `CFLAGS` by default.
