### ISSUE TITLE
curl: add TLS support

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/npg_conda#14]
ubuntu@mg8-test-esa:~/npg_esa/npg_stack$ which curl
/software/npg/20180405/bin/curl

ubuntu@mg8-test-esa:~/npg_esa/npg_stack$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 zlib/1.2.11
Release-Date: 2018-01-24
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp 
Features: AsynchDNS IPv6 Largefile libz UnixSockets

ubuntu@mg8-test-esa:~/npg_esa/npg_stack$ curl  https://glide.sh/get | sh
curl: (1) Protocol "https" not supported or disabled in libcurl

**Comment by keithj** [comment]
Resolved by #16
