### ISSUE TITLE
dated directory: incorrectly linked executables

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/npg_conda#15]
...  due to muliple versions of executables

ubuntu@mg8-test-esa:~/npg_esa/npg_stack$ find /software/pkg/*/*/bin  | grep curl
/software/pkg/bambi/0.10.1/bin/curl-config
/software/pkg/bambi/0.10.1/bin/curl
/software/pkg/bam_stats/1.13.0/bin/curl-config
/software/pkg/bam_stats/1.13.0/bin/curl
/software/pkg/bcftools/1.7/bin/curl-config
/software/pkg/bcftools/1.7/bin/curl
/software/pkg/biobambam2/2.0.79/bin/curl-config
/software/pkg/biobambam2/2.0.79/bin/curl
/software/pkg/curl/7.58.0/bin
/software/pkg/curl/7.58.0/bin/curl-config
/software/pkg/curl/7.58.0/bin/curl
/software/pkg/samtools/1.7/bin/curl-config
/software/pkg/samtools/1.7/bin/curl
/software/pkg/staden_io_lib/1.14.9/bin/curl-config
/software/pkg/staden_io_lib/1.14.9/bin/curl
/software/pkg/tears/1.2.4/bin/curl-config
/software/pkg/tears/1.2.4/bin/curl

ubuntu@mg8-test-esa:~/npg_esa/npg_stack$ readlink "$(which curl)"
/software/pkg/tears/1.2.4/bin/curl

ubuntu@mg8-test-esa:~/npg_esa/npg_stack$ /software/npg/20180405/bin/curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 zlib/1.2.11
Release-Date: 2018-01-24
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp 
Features: AsynchDNS IPv6 Largefile libz UnixSockets 

############ Compare to #############

ubuntu@mg8-test-esa:~/npg_esa/npg_stack$ /usr/bin/curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

**Comment by keithj** [comment]
We can check with `LD_TRACE_LOADED_OBJECTS=1 ldd ./lib/libcurl.so` or just `LD_TRACE_LOADED_OBJECTS=1 curl`

**Comment by keithj** [comment]
This is an interaction between the Conda packages (which do not partition executables and shared libraries into sub-packages) and the install script.
