### ISSUE TITLE
Use official Conda (new) compilers and build tools

### ISSUE THREAD

**Issue by keithj** [wtsi-npg/npg_conda#82]
Move to using the new Conda compilers (supplied by https://github.com/crosstool-ng/crosstool-ng) and using build tools supplied by Conda.

Pro:
- We don't need to build compilers ourselves
- We allow `conda-build` to do more useful linkage checking
- We will have fewer problems when `--error-overlinking` becomes the default behaviour in `conda-build` v4.
- We can build on a very vanilla OS setup having no compiler, `make`, `autoconf`,  etc with reduced risk of accidentally using the host compiler or tools
- We gain the possibility of cross-compiling from `crosstool-ng`

Con:
- Writing recipes is trickier because some build systems do not respect setting the compiler executable via environment variables (e.g. have hard-coded `gcc`)
so
  - We document the tricky parts with examples so that knowledge is spread
  - We submit patches upstream, if appropriate
- The earliest `gcc` in `defaults` is `gcc` `5.4.*` and some software will not build with anything later than `4.8.*`, so
  - We deprecate certain software if we can 
*or*
  - We maintain a fork or patch that software

**Comment by kjsanger** [comment]
Fixed by #113
